/**
 * This class is automatically generated by mig. DO NOT EDIT THIS FILE.
 * This class implements a Java interface to the 'NodeSenseMsg'
 * message type.
 */

public class NodeSenseMsg extends net.tinyos.message.Message {

    /** The default size of this message type in bytes. */
    public static final int DEFAULT_MESSAGE_SIZE = 16;

    /** The Active Message type associated with this message. */
    public static final int AM_TYPE = 147;

    /** Create a new NodeSenseMsg of size 16. */
    public NodeSenseMsg() {
        super(DEFAULT_MESSAGE_SIZE);
        amTypeSet(AM_TYPE);
    }

    /** Create a new NodeSenseMsg of the given data_length. */
    public NodeSenseMsg(int data_length) {
        super(data_length);
        amTypeSet(AM_TYPE);
    }

    /**
     * Create a new NodeSenseMsg with the given data_length
     * and base offset.
     */
    public NodeSenseMsg(int data_length, int base_offset) {
        super(data_length, base_offset);
        amTypeSet(AM_TYPE);
    }

    /**
     * Create a new NodeSenseMsg using the given byte array
     * as backing store.
     */
    public NodeSenseMsg(byte[] data) {
        super(data);
        amTypeSet(AM_TYPE);
    }

    /**
     * Create a new NodeSenseMsg using the given byte array
     * as backing store, with the given base offset.
     */
    public NodeSenseMsg(byte[] data, int base_offset) {
        super(data, base_offset);
        amTypeSet(AM_TYPE);
    }

    /**
     * Create a new NodeSenseMsg using the given byte array
     * as backing store, with the given base offset and data length.
     */
    public NodeSenseMsg(byte[] data, int base_offset, int data_length) {
        super(data, base_offset, data_length);
        amTypeSet(AM_TYPE);
    }

    /**
     * Create a new NodeSenseMsg embedded in the given message
     * at the given base offset.
     */
    public NodeSenseMsg(net.tinyos.message.Message msg, int base_offset) {
        super(msg, base_offset, DEFAULT_MESSAGE_SIZE);
        amTypeSet(AM_TYPE);
    }

    /**
     * Create a new NodeSenseMsg embedded in the given message
     * at the given base offset and length.
     */
    public NodeSenseMsg(net.tinyos.message.Message msg, int base_offset, int data_length) {
        super(msg, base_offset, data_length);
        amTypeSet(AM_TYPE);
    }

    /**
    /* Return a String representation of this message. Includes the
     * message type name and the non-indexed field values.
     */
    public String toString() {
      String s = "Message <NodeSenseMsg> \n";
      try {
        s += "  [version=0x"+Long.toHexString(get_version())+"]\n";
      } catch (ArrayIndexOutOfBoundsException aioobe) { /* Skip field */ }
      try {
        s += "  [interval=0x"+Long.toHexString(get_interval())+"]\n";
      } catch (ArrayIndexOutOfBoundsException aioobe) { /* Skip field */ }
      try {
        s += "  [id=0x"+Long.toHexString(get_id())+"]\n";
      } catch (ArrayIndexOutOfBoundsException aioobe) { /* Skip field */ }
      try {
        s += "  [count=0x"+Long.toHexString(get_count())+"]\n";
      } catch (ArrayIndexOutOfBoundsException aioobe) { /* Skip field */ }
      try {
        s += "  [temperature=";
        for (int i = 0; i < 1; i++) {
          s += "0x"+Long.toHexString(getElement_temperature(i) & 0xffff)+" ";
        }
        s += "]\n";
      } catch (ArrayIndexOutOfBoundsException aioobe) { /* Skip field */ }
      try {
        s += "  [humidity=";
        for (int i = 0; i < 1; i++) {
          s += "0x"+Long.toHexString(getElement_humidity(i) & 0xffff)+" ";
        }
        s += "]\n";
      } catch (ArrayIndexOutOfBoundsException aioobe) { /* Skip field */ }
      try {
        s += "  [illumination=";
        for (int i = 0; i < 1; i++) {
          s += "0x"+Long.toHexString(getElement_illumination(i) & 0xffff)+" ";
        }
        s += "]\n";
      } catch (ArrayIndexOutOfBoundsException aioobe) { /* Skip field */ }
      try {
        s += "  [curtime=";
        for (int i = 0; i < 1; i++) {
          s += "0x"+Long.toHexString(getElement_curtime(i) & 0xffff)+" ";
        }
        s += "]\n";
      } catch (ArrayIndexOutOfBoundsException aioobe) { /* Skip field */ }
      return s;
    }

    // Message-type-specific access methods appear below.

    /////////////////////////////////////////////////////////
    // Accessor methods for field: version
    //   Field type: int, unsigned
    //   Offset (bits): 0
    //   Size (bits): 16
    /////////////////////////////////////////////////////////

    /**
     * Return whether the field 'version' is signed (false).
     */
    public static boolean isSigned_version() {
        return false;
    }

    /**
     * Return whether the field 'version' is an array (false).
     */
    public static boolean isArray_version() {
        return false;
    }

    /**
     * Return the offset (in bytes) of the field 'version'
     */
    public static int offset_version() {
        return (0 / 8);
    }

    /**
     * Return the offset (in bits) of the field 'version'
     */
    public static int offsetBits_version() {
        return 0;
    }

    /**
     * Return the value (as a int) of the field 'version'
     */
    public int get_version() {
        return (int)getUIntBEElement(offsetBits_version(), 16);
    }

    /**
     * Set the value of the field 'version'
     */
    public void set_version(int value) {
        setUIntBEElement(offsetBits_version(), 16, value);
    }

    /**
     * Return the size, in bytes, of the field 'version'
     */
    public static int size_version() {
        return (16 / 8);
    }

    /**
     * Return the size, in bits, of the field 'version'
     */
    public static int sizeBits_version() {
        return 16;
    }

    /////////////////////////////////////////////////////////
    // Accessor methods for field: interval
    //   Field type: int, unsigned
    //   Offset (bits): 16
    //   Size (bits): 16
    /////////////////////////////////////////////////////////

    /**
     * Return whether the field 'interval' is signed (false).
     */
    public static boolean isSigned_interval() {
        return false;
    }

    /**
     * Return whether the field 'interval' is an array (false).
     */
    public static boolean isArray_interval() {
        return false;
    }

    /**
     * Return the offset (in bytes) of the field 'interval'
     */
    public static int offset_interval() {
        return (16 / 8);
    }

    /**
     * Return the offset (in bits) of the field 'interval'
     */
    public static int offsetBits_interval() {
        return 16;
    }

    /**
     * Return the value (as a int) of the field 'interval'
     */
    public int get_interval() {
        return (int)getUIntBEElement(offsetBits_interval(), 16);
    }

    /**
     * Set the value of the field 'interval'
     */
    public void set_interval(int value) {
        setUIntBEElement(offsetBits_interval(), 16, value);
    }

    /**
     * Return the size, in bytes, of the field 'interval'
     */
    public static int size_interval() {
        return (16 / 8);
    }

    /**
     * Return the size, in bits, of the field 'interval'
     */
    public static int sizeBits_interval() {
        return 16;
    }

    /////////////////////////////////////////////////////////
    // Accessor methods for field: id
    //   Field type: int, unsigned
    //   Offset (bits): 32
    //   Size (bits): 16
    /////////////////////////////////////////////////////////

    /**
     * Return whether the field 'id' is signed (false).
     */
    public static boolean isSigned_id() {
        return false;
    }

    /**
     * Return whether the field 'id' is an array (false).
     */
    public static boolean isArray_id() {
        return false;
    }

    /**
     * Return the offset (in bytes) of the field 'id'
     */
    public static int offset_id() {
        return (32 / 8);
    }

    /**
     * Return the offset (in bits) of the field 'id'
     */
    public static int offsetBits_id() {
        return 32;
    }

    /**
     * Return the value (as a int) of the field 'id'
     */
    public int get_id() {
        return (int)getUIntBEElement(offsetBits_id(), 16);
    }

    /**
     * Set the value of the field 'id'
     */
    public void set_id(int value) {
        setUIntBEElement(offsetBits_id(), 16, value);
    }

    /**
     * Return the size, in bytes, of the field 'id'
     */
    public static int size_id() {
        return (16 / 8);
    }

    /**
     * Return the size, in bits, of the field 'id'
     */
    public static int sizeBits_id() {
        return 16;
    }

    /////////////////////////////////////////////////////////
    // Accessor methods for field: count
    //   Field type: int, unsigned
    //   Offset (bits): 48
    //   Size (bits): 16
    /////////////////////////////////////////////////////////

    /**
     * Return whether the field 'count' is signed (false).
     */
    public static boolean isSigned_count() {
        return false;
    }

    /**
     * Return whether the field 'count' is an array (false).
     */
    public static boolean isArray_count() {
        return false;
    }

    /**
     * Return the offset (in bytes) of the field 'count'
     */
    public static int offset_count() {
        return (48 / 8);
    }

    /**
     * Return the offset (in bits) of the field 'count'
     */
    public static int offsetBits_count() {
        return 48;
    }

    /**
     * Return the value (as a int) of the field 'count'
     */
    public int get_count() {
        return (int)getUIntBEElement(offsetBits_count(), 16);
    }

    /**
     * Set the value of the field 'count'
     */
    public void set_count(int value) {
        setUIntBEElement(offsetBits_count(), 16, value);
    }

    /**
     * Return the size, in bytes, of the field 'count'
     */
    public static int size_count() {
        return (16 / 8);
    }

    /**
     * Return the size, in bits, of the field 'count'
     */
    public static int sizeBits_count() {
        return 16;
    }

    /////////////////////////////////////////////////////////
    // Accessor methods for field: temperature
    //   Field type: int[], unsigned
    //   Offset (bits): 64
    //   Size of each element (bits): 16
    /////////////////////////////////////////////////////////

    /**
     * Return whether the field 'temperature' is signed (false).
     */
    public static boolean isSigned_temperature() {
        return false;
    }

    /**
     * Return whether the field 'temperature' is an array (true).
     */
    public static boolean isArray_temperature() {
        return true;
    }

    /**
     * Return the offset (in bytes) of the field 'temperature'
     */
    public static int offset_temperature(int index1) {
        int offset = 64;
        if (index1 < 0 || index1 >= 1) throw new ArrayIndexOutOfBoundsException();
        offset += 0 + index1 * 16;
        return (offset / 8);
    }

    /**
     * Return the offset (in bits) of the field 'temperature'
     */
    public static int offsetBits_temperature(int index1) {
        int offset = 64;
        if (index1 < 0 || index1 >= 1) throw new ArrayIndexOutOfBoundsException();
        offset += 0 + index1 * 16;
        return offset;
    }

    /**
     * Return the entire array 'temperature' as a int[]
     */
    public int[] get_temperature() {
        int[] tmp = new int[1];
        for (int index0 = 0; index0 < numElements_temperature(0); index0++) {
            tmp[index0] = getElement_temperature(index0);
        }
        return tmp;
    }

    /**
     * Set the contents of the array 'temperature' from the given int[]
     */
    public void set_temperature(int[] value) {
        for (int index0 = 0; index0 < value.length; index0++) {
            setElement_temperature(index0, value[index0]);
        }
    }

    /**
     * Return an element (as a int) of the array 'temperature'
     */
    public int getElement_temperature(int index1) {
        return (int)getUIntBEElement(offsetBits_temperature(index1), 16);
    }

    /**
     * Set an element of the array 'temperature'
     */
    public void setElement_temperature(int index1, int value) {
        setUIntBEElement(offsetBits_temperature(index1), 16, value);
    }

    /**
     * Return the total size, in bytes, of the array 'temperature'
     */
    public static int totalSize_temperature() {
        return (16 / 8);
    }

    /**
     * Return the total size, in bits, of the array 'temperature'
     */
    public static int totalSizeBits_temperature() {
        return 16;
    }

    /**
     * Return the size, in bytes, of each element of the array 'temperature'
     */
    public static int elementSize_temperature() {
        return (16 / 8);
    }

    /**
     * Return the size, in bits, of each element of the array 'temperature'
     */
    public static int elementSizeBits_temperature() {
        return 16;
    }

    /**
     * Return the number of dimensions in the array 'temperature'
     */
    public static int numDimensions_temperature() {
        return 1;
    }

    /**
     * Return the number of elements in the array 'temperature'
     */
    public static int numElements_temperature() {
        return 1;
    }

    /**
     * Return the number of elements in the array 'temperature'
     * for the given dimension.
     */
    public static int numElements_temperature(int dimension) {
      int array_dims[] = { 1,  };
        if (dimension < 0 || dimension >= 1) throw new ArrayIndexOutOfBoundsException();
        if (array_dims[dimension] == 0) throw new IllegalArgumentException("Array dimension "+dimension+" has unknown size");
        return array_dims[dimension];
    }

    /////////////////////////////////////////////////////////
    // Accessor methods for field: humidity
    //   Field type: int[], unsigned
    //   Offset (bits): 80
    //   Size of each element (bits): 16
    /////////////////////////////////////////////////////////

    /**
     * Return whether the field 'humidity' is signed (false).
     */
    public static boolean isSigned_humidity() {
        return false;
    }

    /**
     * Return whether the field 'humidity' is an array (true).
     */
    public static boolean isArray_humidity() {
        return true;
    }

    /**
     * Return the offset (in bytes) of the field 'humidity'
     */
    public static int offset_humidity(int index1) {
        int offset = 80;
        if (index1 < 0 || index1 >= 1) throw new ArrayIndexOutOfBoundsException();
        offset += 0 + index1 * 16;
        return (offset / 8);
    }

    /**
     * Return the offset (in bits) of the field 'humidity'
     */
    public static int offsetBits_humidity(int index1) {
        int offset = 80;
        if (index1 < 0 || index1 >= 1) throw new ArrayIndexOutOfBoundsException();
        offset += 0 + index1 * 16;
        return offset;
    }

    /**
     * Return the entire array 'humidity' as a int[]
     */
    public int[] get_humidity() {
        int[] tmp = new int[1];
        for (int index0 = 0; index0 < numElements_humidity(0); index0++) {
            tmp[index0] = getElement_humidity(index0);
        }
        return tmp;
    }

    /**
     * Set the contents of the array 'humidity' from the given int[]
     */
    public void set_humidity(int[] value) {
        for (int index0 = 0; index0 < value.length; index0++) {
            setElement_humidity(index0, value[index0]);
        }
    }

    /**
     * Return an element (as a int) of the array 'humidity'
     */
    public int getElement_humidity(int index1) {
        return (int)getUIntBEElement(offsetBits_humidity(index1), 16);
    }

    /**
     * Set an element of the array 'humidity'
     */
    public void setElement_humidity(int index1, int value) {
        setUIntBEElement(offsetBits_humidity(index1), 16, value);
    }

    /**
     * Return the total size, in bytes, of the array 'humidity'
     */
    public static int totalSize_humidity() {
        return (16 / 8);
    }

    /**
     * Return the total size, in bits, of the array 'humidity'
     */
    public static int totalSizeBits_humidity() {
        return 16;
    }

    /**
     * Return the size, in bytes, of each element of the array 'humidity'
     */
    public static int elementSize_humidity() {
        return (16 / 8);
    }

    /**
     * Return the size, in bits, of each element of the array 'humidity'
     */
    public static int elementSizeBits_humidity() {
        return 16;
    }

    /**
     * Return the number of dimensions in the array 'humidity'
     */
    public static int numDimensions_humidity() {
        return 1;
    }

    /**
     * Return the number of elements in the array 'humidity'
     */
    public static int numElements_humidity() {
        return 1;
    }

    /**
     * Return the number of elements in the array 'humidity'
     * for the given dimension.
     */
    public static int numElements_humidity(int dimension) {
      int array_dims[] = { 1,  };
        if (dimension < 0 || dimension >= 1) throw new ArrayIndexOutOfBoundsException();
        if (array_dims[dimension] == 0) throw new IllegalArgumentException("Array dimension "+dimension+" has unknown size");
        return array_dims[dimension];
    }

    /////////////////////////////////////////////////////////
    // Accessor methods for field: illumination
    //   Field type: int[], unsigned
    //   Offset (bits): 96
    //   Size of each element (bits): 16
    /////////////////////////////////////////////////////////

    /**
     * Return whether the field 'illumination' is signed (false).
     */
    public static boolean isSigned_illumination() {
        return false;
    }

    /**
     * Return whether the field 'illumination' is an array (true).
     */
    public static boolean isArray_illumination() {
        return true;
    }

    /**
     * Return the offset (in bytes) of the field 'illumination'
     */
    public static int offset_illumination(int index1) {
        int offset = 96;
        if (index1 < 0 || index1 >= 1) throw new ArrayIndexOutOfBoundsException();
        offset += 0 + index1 * 16;
        return (offset / 8);
    }

    /**
     * Return the offset (in bits) of the field 'illumination'
     */
    public static int offsetBits_illumination(int index1) {
        int offset = 96;
        if (index1 < 0 || index1 >= 1) throw new ArrayIndexOutOfBoundsException();
        offset += 0 + index1 * 16;
        return offset;
    }

    /**
     * Return the entire array 'illumination' as a int[]
     */
    public int[] get_illumination() {
        int[] tmp = new int[1];
        for (int index0 = 0; index0 < numElements_illumination(0); index0++) {
            tmp[index0] = getElement_illumination(index0);
        }
        return tmp;
    }

    /**
     * Set the contents of the array 'illumination' from the given int[]
     */
    public void set_illumination(int[] value) {
        for (int index0 = 0; index0 < value.length; index0++) {
            setElement_illumination(index0, value[index0]);
        }
    }

    /**
     * Return an element (as a int) of the array 'illumination'
     */
    public int getElement_illumination(int index1) {
        return (int)getUIntBEElement(offsetBits_illumination(index1), 16);
    }

    /**
     * Set an element of the array 'illumination'
     */
    public void setElement_illumination(int index1, int value) {
        setUIntBEElement(offsetBits_illumination(index1), 16, value);
    }

    /**
     * Return the total size, in bytes, of the array 'illumination'
     */
    public static int totalSize_illumination() {
        return (16 / 8);
    }

    /**
     * Return the total size, in bits, of the array 'illumination'
     */
    public static int totalSizeBits_illumination() {
        return 16;
    }

    /**
     * Return the size, in bytes, of each element of the array 'illumination'
     */
    public static int elementSize_illumination() {
        return (16 / 8);
    }

    /**
     * Return the size, in bits, of each element of the array 'illumination'
     */
    public static int elementSizeBits_illumination() {
        return 16;
    }

    /**
     * Return the number of dimensions in the array 'illumination'
     */
    public static int numDimensions_illumination() {
        return 1;
    }

    /**
     * Return the number of elements in the array 'illumination'
     */
    public static int numElements_illumination() {
        return 1;
    }

    /**
     * Return the number of elements in the array 'illumination'
     * for the given dimension.
     */
    public static int numElements_illumination(int dimension) {
      int array_dims[] = { 1,  };
        if (dimension < 0 || dimension >= 1) throw new ArrayIndexOutOfBoundsException();
        if (array_dims[dimension] == 0) throw new IllegalArgumentException("Array dimension "+dimension+" has unknown size");
        return array_dims[dimension];
    }

    /////////////////////////////////////////////////////////
    // Accessor methods for field: curtime
    //   Field type: int[], unsigned
    //   Offset (bits): 112
    //   Size of each element (bits): 16
    /////////////////////////////////////////////////////////

    /**
     * Return whether the field 'curtime' is signed (false).
     */
    public static boolean isSigned_curtime() {
        return false;
    }

    /**
     * Return whether the field 'curtime' is an array (true).
     */
    public static boolean isArray_curtime() {
        return true;
    }

    /**
     * Return the offset (in bytes) of the field 'curtime'
     */
    public static int offset_curtime(int index1) {
        int offset = 112;
        if (index1 < 0 || index1 >= 1) throw new ArrayIndexOutOfBoundsException();
        offset += 0 + index1 * 16;
        return (offset / 8);
    }

    /**
     * Return the offset (in bits) of the field 'curtime'
     */
    public static int offsetBits_curtime(int index1) {
        int offset = 112;
        if (index1 < 0 || index1 >= 1) throw new ArrayIndexOutOfBoundsException();
        offset += 0 + index1 * 16;
        return offset;
    }

    /**
     * Return the entire array 'curtime' as a int[]
     */
    public int[] get_curtime() {
        int[] tmp = new int[1];
        for (int index0 = 0; index0 < numElements_curtime(0); index0++) {
            tmp[index0] = getElement_curtime(index0);
        }
        return tmp;
    }

    /**
     * Set the contents of the array 'curtime' from the given int[]
     */
    public void set_curtime(int[] value) {
        for (int index0 = 0; index0 < value.length; index0++) {
            setElement_curtime(index0, value[index0]);
        }
    }

    /**
     * Return an element (as a int) of the array 'curtime'
     */
    public int getElement_curtime(int index1) {
        return (int)getUIntBEElement(offsetBits_curtime(index1), 16);
    }

    /**
     * Set an element of the array 'curtime'
     */
    public void setElement_curtime(int index1, int value) {
        setUIntBEElement(offsetBits_curtime(index1), 16, value);
    }

    /**
     * Return the total size, in bytes, of the array 'curtime'
     */
    public static int totalSize_curtime() {
        return (16 / 8);
    }

    /**
     * Return the total size, in bits, of the array 'curtime'
     */
    public static int totalSizeBits_curtime() {
        return 16;
    }

    /**
     * Return the size, in bytes, of each element of the array 'curtime'
     */
    public static int elementSize_curtime() {
        return (16 / 8);
    }

    /**
     * Return the size, in bits, of each element of the array 'curtime'
     */
    public static int elementSizeBits_curtime() {
        return 16;
    }

    /**
     * Return the number of dimensions in the array 'curtime'
     */
    public static int numDimensions_curtime() {
        return 1;
    }

    /**
     * Return the number of elements in the array 'curtime'
     */
    public static int numElements_curtime() {
        return 1;
    }

    /**
     * Return the number of elements in the array 'curtime'
     * for the given dimension.
     */
    public static int numElements_curtime(int dimension) {
      int array_dims[] = { 1,  };
        if (dimension < 0 || dimension >= 1) throw new ArrayIndexOutOfBoundsException();
        if (array_dims[dimension] == 0) throw new IllegalArgumentException("Array dimension "+dimension+" has unknown size");
        return array_dims[dimension];
    }

}
